---
- name: Google Chrome | Red Hat | Pre requirements
  yum:
    name: gnupg
    state: present

- name: Google Chrome | Red Hat | Apt Repository
  yum_repository:
    name: epel
    description: Google Chrome Repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub

- name: Google Chrome | Red Hat | Installing latest version
  yum:
    name: google-chrome-stable
  when:
    - version is not defined

- name: Google Chrome | Red Hat | Installing version "{{ version }}"
  yum:
    name: "google-chrome-stable={{ version }}"
  when:
    - version is defined
